name: flutter_animarker
description: Marker Geo-Animation solution for Google Maps. Support Linear Animation, Multi-point animation, Rotation and Ripple Effect. Useful for Uber-like application, tracking and other maps driving solutions.
version: 3.4.0-beta.1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.9.2
  vector_math: ^2.1.4
  diffutil_dart: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  import_sorter: ^4.6.0
  dart_test_matchers: ^0.2.0
  google_maps_flutter: 2.2.6
  benchmark_harness: ^2.2.2
